# VARIABLES
# ---------
name:           dennistenen
url:            http://dennistenen.com
description:    "Dennis Tenen's personal blog and portfolio"
keywords:       "Digital Humanities, New Media Studies"
rss:            "dennistenen.com blog feed"
author:         Dennis Tenen
email:          idea@dennistenen.com
# ---------
github:         https://github.com/denten
githubsource:   https://github.com/denten/denten.github.io
twitter:        https://twitter.com/dennistenen
twitter_name:   dennistenen
googleplus:     https://plus.google.com/104493012600393944123/
# ---------
ga:             UA-31694981-1
summary:        true


# JEKYLL
# ---------
exclude:        [README.md, Rakefile]
permalink:      /:year/:month/:day/:title/
pygments:       true
paginate:       5
markdown:       rdiscount


# PLUGINS
# -------
lessc:          lessc --yui-compress
redirects:      yes
