# VARIABLES
# ---------
name:           test 
url:            github.denten.io
description:    ""
keywords:       ""
rss:            ""
author:         Dennis Tenen
email:          denten@gmail.com
# ---------
about:          http://about.me/antoinecorcy
github:         https://github.com/denten
githubsource:   https://github.com/denten/denten.github.io
twitter:        https://twitter.com/toin0u
twitter_name:   dennistenen 
googleplus:     https://plus.google.com//
facebook:       https://
# ---------
ga:             UA-31694981-1
summary:        true


# JEKYLL
# ---------
exclude:        [README.md, Rakefile]
permalink:      /:year/:month/:day/:title/
pygments:       true
paginate:       5
markdown:       rdiscount


# PLUGINS
# -------
lessc:          lessc --yui-compress
redirects:      yes
