# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dennis Tenen 
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com

author:
  name:           'Dennis Tenen'
  url:            https://twitter.com/dennistenen

paginate:         5

# Custom vars

github:
  repo:           https://github.com/denten/denten.github.io
